

obj-y = stub_common.o \
		stub_atomic.o stub_spinlock.o stub_dma.o \
		stub_time.o stub_io.o \
		lib/ctype.o lib/hexdump.o \
		lib/list_debug.o \
		lib/hweight.o lib/bitmap.o\
		lib/dynamic_queue_limits.o \
		lib/devres.o \
		lib/iomap.o lib/pci-iomap.o \
		kernel/cpu.o kernel/workqueue.o \
		kernel/panic.o \
		kernel/irq/manage.o \
		kernel/locking/mutex.o \
		kernel/time/timer.o \
		kernel/printk/printk.o \
		mm/page_alloc.o mm/swap.o mm/slub.o \
		mm/util.o \
		drivers/base/core.o drivers/base/devres.o \
		drivers/base/platform.o \
		drivers/of/base.o \
		drivers/regmap/regmap.o \
		drivers/char/random.o \
		drivers/acpi/property.o \
		drivers/acpi/acpica/nsxfeval.o \
		drivers/pci/pci.o \
		drivers/pci/msi.o \
		drivers/pci/iov.o \
		drivers/pci/pci-driver.o \
		net/core/dev.o net/core/ethtool.o \
		net/core/dev_addr_lists.o net/core/skbuff.o \
		net/core/rtnetlink.o \
		net/sched/sch_generic.o \
		net/ethernet/eth.o \
		net/phy/phy.o net/phy/phy_device.o net/phy/mdio_bus.o \
		net/ipv6/exthdrs_core.o \
		fs/debugfs/inode.o
