/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef KMC_SRC_SDP_SDPV2_ITF_H
#define KMC_SRC_SDP_SDPV2_ITF_H

#include "wsecv2_type.h"
#include "sdpv3_type.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

/* Key derivation length */
#define SDP_HMAC_DERIVE_KEY_LEN 16u
#define SDP_HMAC_HEAD_LEN_V2    70 // SDP_HMAC_HEAD_LEN_V2 is sizeof(SdpHmacExHeaderEx) + 8 bytes(reserve)
#define SDP_CIPHER_HEAD_LEN_V2  72 // SDP_CIPHER_HEAD_LEN_V2 is sizeof(SdpCipherHeaderEx) + 8 bytes(reserve)
#define SDP_PWD_HEAD_LEN_EX     60 // SDP_PWD_HEAD_LEN_EX is sizeof(SdpPwdHeaderEx) + 8 bytes(reserve)
/* Structure */
/* Ciphertext Header Definition */
#pragma pack(1)


typedef struct TagSdpCipherHeaderEx {
    WsecUint32    cipherVersion;
    WsecUint32    hmacFlag;    /* Determine whether to add HMAC */
    WsecUint32    domainId;
    WsecUint32    keyId;
    WsecUint32    cipherAlgId;
    unsigned char mkHashId[WSEC_MK_HASH_REC_LEN]; /* The first eight bytes of the MK SHA256. */
    unsigned char salt[SDP_SALT_LEN_V2];     /* The salt value is 8 bytes. */
    unsigned char iv[16];      /* IV: 16 bytes */
    unsigned char kdfAlgId;    /* Used to get work key */
    unsigned char iter[3];     /* The iteration rounds to get work key */
    WsecUint32    extLen;
    WsecUint32    ciphertextLen;
} SdpCipherHeaderEx;

typedef struct TagSdpHmacHeaderEx {
    WsecUint32    hmacAlgId;  /* HMAC algorithm */
    unsigned char salt[8];    /* The salt value of the generated key is 8 bytes. */
    WsecUint32    extLen; /* 4 bytes are reserved. */
    WsecUint32    hmacLen;    /* Indicates the length of an HMAC. */
} SdpHmacHeaderEx;
#pragma pack()

#pragma pack(1)
typedef struct TagSdpHmacExHeaderEx {
    WsecUint32      version;            /* Data protection module version */
    WsecUint32      domain;             /* Field corresponding to the key ID */
    WsecUint32      algId;              /* Algorithm ID */
    WsecUint32      keyId;              /* Key ID used to calculate the HMAC */
    WsecUint32      kdfIter;
    WsecUint32      kdfAlgId;
    unsigned char   salt[SDP_SALT_LEN];
    unsigned char   mkHash[WSEC_MK_HASH_REC_LEN];
    WsecUint32      extLen;
    unsigned char   reserve[12];
} SdpHmacExHeaderEx;
#pragma pack()

#pragma pack(1)
typedef struct TagSdpHmacAlgAttributesEx {
    union {
        unsigned char buff[SDP_HMAC_HEAD_LEN_V2];
        SdpHmacExHeaderEx hmacHeader;
    };
} SdpHmacAlgAttributesEx;
#pragma pack()

#pragma pack(1)
typedef struct TagSdpCipherHeaderBuffEx {
    union {
        unsigned char   buff[SDP_CIPHER_HEAD_LEN_V2];
        SdpCipherHeaderEx cipherHeader;
    };
} SdpCipherHeaderBuffEx;
#pragma pack()

#pragma pack(1)
typedef struct TagSdpBodCipherHeaderEx {
    SdpCipherHeaderBuffEx  cipherBuff;
    SdpHmacAlgAttributesEx hmacBuff;
    WsecUint32 extLen;
    unsigned char reserve[12];
} SdpBodCipherHeaderEx;
#pragma pack()

#pragma pack(1)
typedef struct TagSdpPwdHeaderEx {
    WsecUint32    version;            /* Data protection module version */
    WsecUint32    algId;              /* Algorithm ID */
    /* Iteration round, which is configured by the application for the key management module to derive working keys. */
    WsecUint32    iter;
    unsigned char salt[SDP_SALT_LEN]; /* Salt generated by the data protection module. */
    WsecUint32    cipherLen;          /* Length of the encrypted password */
    WsecUint32    extLen;
    unsigned char reserve[16];
} SdpPwdHeaderEx;
#pragma pack()

typedef struct TagSdpBodCipherInfoSt {
    WsecUint32 cipherAlgId;
    WsecUint32 hasHmac;
    WsecUint32 hmacAlgId;
    unsigned char reserve[20];
} SdpBodCipherInfo;

typedef struct TagSdpCipherCnfParam {
    WsecUint32    domain;
    WsecUint32    cipherAlgId;
    WsecUint32    hmacAlgId;
} SdpCipherCnfParam;

/* API Function Prototype Declaration */
/* Specify the domain and encryption algorithm ID, encrypt the specified plaintext, and obtain the ciphertext. */
unsigned long SdpEncryptEx(WsecUint32 domain, WsecUint32 algId,
    const unsigned char *plainText, WsecUint32 plaintextLen,
    unsigned char *ciphertext, WsecUint32 *ciphertextLen);

/* Decrypts the specified ciphertext data. The data with or without the HMAC can be decrypted. */
unsigned long SdpDecryptEx(WsecUint32 domain,
    const unsigned char *ciphertext, WsecUint32 ciphertextLen,
    unsigned char *plainText, WsecUint32 *plaintextLen);

/*
 * Specify the domain and encryption/MAC algorithm ID, encrypt the specified plaintext,
 * calculate the MAC, and obtain the ciphertext.
 */
unsigned long SdpEncryptWithHmacEx(WsecUint32 domain,
    WsecUint32 cipherAlgId, WsecUint32 hmacAlgId,
    const unsigned char *plainText, WsecUint32 plaintextLen,
    unsigned char *ciphertext, WsecUint32 *ciphertextLen);

/*
 * Specify the domain and encryption/MAC algorithm ID, encrypt the specified plaintext,
 * calculate the MAC, and obtain the ciphertext.
 * Note
 * This interface is used to resolve the problem that the HMAC key length of the SdpEncryptWithHmacEx
 * interface is insufficient, but the interface is incompatible.
 * The application scenarios of the SDP_DecryptEx interface in the old version are as follows,
 * 1. In the scenario where the KMC is deployed on multiple nodes (only V2 supports the deployment on multiple nodes),
 * this interface is used for newly deployed nodes.
 * In the scenario where SdpEncryptWithHmacV3 is used for encryption and the old node uses SDP_DecryptEx
 * in the old version for decryption,
 * SdpEncryptWithHmacV3 is incompatible with SDP_DecryptEx in earlier versions.
 * SDP_DecryptEx cannot decrypt data encrypted by SdpEncryptWithHmacV3.
 * SdpEncryptWithHmacV3
 * 2. In the version rollback scenario, after the data encrypted using SdpEncryptWithHmacV3 is rolled
 * back to the source version,
 * SDP_DecryptEx Failed to Decrypt the Newly Encrypted SdpEncryptWithHmacV3 Data
 * Therefore, for a single-node system, SdpEncryptWithHmacV3 is upgraded for multiple nodes,
 * or only old nodes are encrypted.
 * In the scenarios where new nodes are deployed for decryption, the SdpEncryptWithHmacV3 encryption
 * algorithm that cannot be decrypted after the rollback is considered.
 * The new SdpEncryptWithHmacV3 interface should be used after the risk of the output data is eliminated.
 */
unsigned long SdpEncryptWithHmacV3(WsecUint32 domain,
    WsecUint32 cipherAlgId, WsecUint32 hmacAlgId,
    const unsigned char *plainText, WsecUint32 plaintextLen,
    unsigned char *ciphertext, WsecUint32 *ciphertextLen);

/* Obtains the length of the ciphertext data corresponding to the plaintext data when HMAC is not calculated. */
unsigned long SdpGetCipherDataLenEx(WsecUint32 plaintextLen, WsecUint32 *ciphertextLenOut);

/* Obtains the length of the ciphertext data, algCnf MUST be same as the configuration of WsecInitializeKmc */
unsigned long SdpGetCipherDataLenExByAlgCnf(const KmcAlgCnfParam *algCnf, WsecUint32 plaintextLen,
    WsecUint32 *ciphertextLen);

/* Obtains the length of the ciphertext data corresponding to the plaintext data when HMAC is calculated. */
unsigned long SdpGetCipherDataLenWithHmacEx(WsecUint32 plaintextLen, WsecUint32 *ciphertextLenOut);

/* Obtains the header structure of the input ciphertext. */
unsigned long SdpGetCipherHeaderEx(const unsigned char *ciphertext, WsecUint32 ciphertextLen,
    SdpCipherHeaderEx *cipherHeader);

/* Obtain MKInfo based on the obtained ciphertext information. */
unsigned long SdpGetMkDetailByCipher(const unsigned char *cipherData, WsecUint32 cipherDataLen, KmcMkInfo *mkInfo);

/* according to passwordHashLen get pwdCipherLen  */
size_t SdpGetPwdCipherLenEx(size_t passwordHashLen);

/* according to passwordHashLen get pwdCipherLen */
unsigned long  SdpGetPwdCipherLenV3(WsecUint32 passwordHashLen, WsecUint32 *pwdCipherLen);

/* Protection password */
unsigned long SdpProtectPwdEx(WsecUint32 algId, WsecUint32 iter, const unsigned char *plain, WsecUint32 plainLen,
    unsigned char *cipher, WsecUint32 cipherLen);

/* Plaintext password authentication */
unsigned long SdpVerifyPwdEx(const unsigned char *plainText, WsecUint32 plainLen,
    const unsigned char *cipherText, WsecUint32 cipherLen);

/* Obtains MKInfo based on hmacData. */
unsigned long SdpGetMkDetailByHmacDataEx(WsecVoid *hmacData, WsecUint32 hmacLen, KmcMkInfo *mkInfo);

/* Get mac len by symAlgId and hmacAlgId */
unsigned long SdpGetMacLenForEncryptEx(WsecUint32 cipherAlgId, WsecUint32 hmacAlgId, WsecUint32 *macLen);

/* Calculates the HMAC of the specified data using the key in the specified domain and the specified algorithm ID. */
unsigned long SdpHmacEx(WsecUint32 domain, WsecUint32 algId, const unsigned char *plainText, WsecUint32 plaintextLen,
    unsigned char *hmacData, WsecUint32 *hmacLen);

/* Check whether the HMAC result is correct. */
unsigned long SdpVerifyHmacEx(WsecUint32 domain, const unsigned char *plainText, WsecUint32 plaintextLen,
    const unsigned char *hmacData, WsecUint32 hmacLen);

/* Obtains the maximum possible HMAC length. */
unsigned long SdpGetHmacLenEx(WsecUint32 *hmacLen);

/* Get hmac header len by version or header before decrypt, header only support sdp v2 */
unsigned long SdpDecGetHmacHeaderLen(const unsigned char *verBuff, WsecUint32 verLen, WsecUint32 *outLen);

/* Get BodcipherHeaderLen by version before decrypt */
unsigned long SdpDecGetBodHeaderLen(const unsigned char *verBuff, WsecUint32 verBuffLen, WsecUint32 *outLen);

/* Get HmacHeaderLen by version before encrypt */
WsecUint32 SdpEncGetHamcHeaderLen(void);

unsigned long SdpEncGetHmacHeaderLenV3(WsecUint32 *outLen);

/* Get BodcipherHeaderLen by version before encrypt */
WsecUint32 SdpEncGetBodHeaderLen(void);

/* Get BodcipherHeaderLen by version before encrypt */
unsigned long SdpEncGetBodHeaderLenV3(WsecUint32 cipherAlgId, WsecUint32 hmacAlgId, WsecUint32 *outLen);

unsigned long SdpHmacInitEx(WsecUint32 domain, const void *hmacAlgAttributes, WsecUint32 attrLen, WsecHandle *ctx);

unsigned long SdpHmacUpdateEx(WsecHandle *ctx, const unsigned char *plainText, WsecUint32 plaintextLen);

unsigned long SdpHmacFinalEx(WsecHandle *ctx, unsigned char *hmacData, WsecUint32 *hmacLen);

unsigned long SdpFileHmacEx(WsecUint32 domain, const char *file, const SdpHmacAlgAttributesEx *hmacAlgAttributes,
    WsecVoid *hmacData, WsecUint32 *hmacLen);
unsigned long SdpFileHmacV3(WsecUint32 domain, const char *file, WsecBuffConst *hmacAlgAttributes,
    WsecVoid *hmacData, WsecUint32 *hmacLen);

unsigned long SdpVerifyFileHmacEx(WsecUint32 domain, const char *file, const void *hmacAlgAttributes,
    WsecUint32 attrLen, const WsecVoid *hmacData, WsecUint32 hmacLen);

unsigned long SdpGetHmacAlgAttrEx(WsecUint32 domain, WsecUint32 algId, SdpHmacAlgAttributesEx *hmacAlgAttributes);

unsigned long SdpGetHmacAlgAttrV3(WsecUint32 domain, WsecUint32 algId, WsecVoid *hmacAlgAttributes,
    WsecUint32 *attrLen);

unsigned long SdpEncryptInitEx(WsecUint32 domain, WsecUint32 cipherAlgId, WsecUint32 hmacAlgId, WsecHandle *ctx,
    SdpBodCipherHeaderEx *bodCipherHeader);

unsigned long SdpEncryptInitV3(SdpCipherCnfParam *cipherCnf, WsecHandle *ctx, WsecBuff *bodCipherHeader);

unsigned long SdpEncryptUpdateEx(WsecHandle *ctx, const unsigned char *plainText, WsecUint32 plainLen,
    unsigned char *cipherText, WsecUint32 *cipherLen);

unsigned long SdpEncryptFinalEx(WsecHandle *ctx, unsigned char *cipherText, WsecUint32 *cipherLen,
    unsigned char *hmacText, WsecUint32 *hmacLen);

unsigned long SdpDecryptInitEx(WsecUint32 domain, WsecHandle *ctx, const WsecVoid *bodCipherHeader,
    WsecUint32 bodHeaderLen);

unsigned long SdpDecryptUpdateEx(WsecHandle *ctx, const unsigned char *cipherText, WsecUint32 cipherLen,
    unsigned char *plainText, WsecUint32 *plainLen);

unsigned long SdpDecryptFinalEx(WsecHandle *ctx, const unsigned char *hmacText, WsecUint32 hmacLen,
    unsigned char *plainText, WsecUint32 *plainLen);


unsigned long SdpFileEncryptEx(WsecUint32 domain, WsecUint32 cipherAlgId, WsecUint32 hmacAlgId,
    const char *plainFile, const char *cipherFile, const CallbackGetFileDateTime getFileDateTime);

unsigned long SdpFileDecryptEx(WsecUint32 domain, const char *cipherFile, const char *plainFile,
    const CallbackSetFileDateTime setFileDateTime);

/* Obtain the encryption infomation of the ciphertext file. */
unsigned long SdpGetCipherInfoFromBodHeader(const unsigned char *bodCipherHeader, WsecUint32 bodCipherHeaderLen,
    SdpBodCipherInfo* cipherInfo);

unsigned long SdpGetMkDetailByBodCipherHeaderEx(WsecVoid *bodCipherHeader, WsecUint32 bodCipherLen, KmcMkInfo *mkInfo);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* KMC_SRC_SDP_SDPV2_ITF_H */
